### ISSUE TITLE
Document usage for EpochTester.convert

### ISSUE THREAD

**Issue by martinvw** [martinvw/epoch-analyzer#1]
Currently the readme does not describe the usage of EpochTester.convert.

**Comment by martinvw** [comment]
The documentation in the repo is updated, release a new version in pip.

**Comment by richmans** [comment]
Zozo! Lekker bezig! We hebben nog een opening voor een specialist
programmeur hoor :-)

**Comment by martinvw** [comment]
0.4 has been released yesterday, this resolves this issue

**Comment by martinvw** [comment]
Ha Richard,

Ik raakte erg gemotiveerd toen ik zag dat de laatst maand het project 148x
gedownload was via PiP. Hoe is het met jou en bij jullie? Ik ben wel lekker
aan het werk, heb nu een leuk Java project voor de Rabobank.

Zullen we binnenkort eens bijpraten?

Groetjes,

Martin

Op zaterdag 16 april 2016 heeft Richard Bronkhorst <notifications@github.com>
het volgende geschreven:
